### ISSUE TITLE
any plan to migrate to netstandard?

### ISSUE THREAD

**Issue by DGuidi** [NancyFx/Nancy.MSOwinSecurity#14]
I'm not sure to understand if this code isn't migrated yer to netstandard because of lack of time or perhaps because it's not needed anymore.
I've some code that use this lib and works like a charm in full framework: now that I'm trying to migrate to netstandard, I don't understand how to convert this code.
Any help would be appreciated, thanks.

**Comment by damianh** [comment]
This project depends on [Microsoft.Owin.Security](https://github.com/NancyFx/Nancy.MSOwinSecurity/blob/master/src/Nancy.MSOwinSecurity/Nancy.MSOwinSecurity.nuspec#L16) which is net451 only. While it is completely possible, MS won't be updating their `Microsoft.Owin` package to netstandard because they'd prefer people to stop using is.

oh well.

**Comment by DGuidi** [comment]
any migration suggestion? asp.net core, I think...
