### ISSUE TITLE
Question - JWT and/or Token Auth

### ISSUE THREAD

**Issue by sgentile** [NancyFx/Nancy.MSOwinSecurity#6]
I'm trying to determine if this is the correct solution (the MSOwinSecurity) - I want to use a similiar setup outlined here http://bitoftech.net/2014/10/27/json-web-token-asp-net-web-api-2-jwt-owin-authorization-server/ but with Nancy.

Is this possible ?

**Comment by damianh** [comment]
Yes the same all the way 'till step `Step 2.4: Add new protected controller`. Instead of `[Authorize]` use [`RequiresMSOwinAuthentication`](https://github.com/NancyFx/Nancy.MSOwinSecurity/blob/master/src/Nancy.MSOwinSecurity/NancyModuleExtensions.cs#L15). Good news is that the upcoming Nancy 2.0 has ClaimsPrincipal support baked in, which will obsolete this lib.

(Sorry for the slow response, dropped off my radar).

**Comment by sgentile** [comment]
Thanks
